package com.example.facetracking3d.graphics.gl

import android.opengl.GLES30

// The "Math Engine." GLSL (OpenGL Shading Language) runs in parallel on the GPU's thousands of cores.
// We do the green alpha mask here

object YuvShaderUtil {

    // =========================================================================
    // PASS 1: THE COPIER (Hardware OES -> Hidden Frame Buffer)
    // =========================================================================
    const val COPY_VERTEX_SHADER = """#version 300 es
        in vec4 aPosition;
        in vec2 aTextureCoord;
        uniform mat4 uTransformMatrix; 
        out vec2 vTexCoord;
        void main() {
            gl_Position = aPosition;
            
            // The Android camera hardware feeds us a texture that is physically rotated 90 degrees.
            // uTransformMatrix is a matrix generated by Android that contains the fix.
            vec2 hwCoord = (uTransformMatrix * vec4(aTextureCoord, 0.0, 1.0)).xy;
            
            // We swap X and Y to rotate the video upright, so it is saved perfectly 
            // oriented inside our hidden FBO Ring Buffer.
            vTexCoord = vec2(1.0 - hwCoord.y, 1.0 - hwCoord.x);
        }
    """

    const val COPY_FRAGMENT_SHADER = """#version 300 es
        // This extension is required to read Android's proprietary OES hardware textures.
        #extension GL_OES_EGL_image_external_essl3 : require
        precision mediump float;
        in vec2 vTexCoord;
        out vec4 FragColor;
        
        uniform samplerExternalOES uCameraTexture;
        void main() {
            // Sample the pixel from the camera sensor and output it to the FBO.
            FragColor = texture(uCameraTexture, vTexCoord);
        }
    """

    // =========================================================================
    // PASS 2: THE COMPOSITOR (Hidden Frame Buffer + Mask -> Screen)
    // =========================================================================
    const val COMP_VERTEX_SHADER = """#version 300 es
in vec4 aPosition;
        in vec2 aTextureCoord;
        
        uniform int uMirror; 
        
        out vec2 vCameraCoord;
        out vec2 vMaskCoord;
        
        void main() {
            gl_Position = aPosition;
            vec2 finalCoord = aTextureCoord; 
            
            // Just flip the X-axis if the mirror is enabled
            if (uMirror == 1) {
                finalCoord.x = 1.0 - finalCoord.x;
            }
            
            vCameraCoord = finalCoord;
            vMaskCoord = vec2(finalCoord.x, 1.0 - finalCoord.y);
        }
    """

    const val COMP_FRAGMENT_SHADER = """#version 300 es
        precision mediump float;
        in vec2 vCameraCoord;
        in vec2 vMaskCoord;
        out vec4 FragColor;
        
        uniform sampler2D uCameraTexture; 
        uniform sampler2D uMaskTexture;
        uniform int uEnableGreenScreen;
        
        uniform vec2 uFeatherThresholds; 
        
        void main() {
            vec4 cameraColor = texture(uCameraTexture, vCameraCoord);
            
            if (uEnableGreenScreen == 1) {
                vec2 offset = vec2(3.0 / 1280.0, 3.0 / 720.0);
                
                float center = texture(uMaskTexture, vMaskCoord).r;
                float up     = texture(uMaskTexture, vMaskCoord + vec2(0.0, offset.y)).r;
                float down   = texture(uMaskTexture, vMaskCoord + vec2(0.0, -offset.y)).r;
                float left   = texture(uMaskTexture, vMaskCoord + vec2(-offset.x, 0.0)).r;
                float right  = texture(uMaskTexture, vMaskCoord + vec2(offset.x, 0.0)).r;
                
                float blurredConfidence = (center + up + down + left + right) / 5.0;
                
                float alpha = smoothstep(uFeatherThresholds.x, uFeatherThresholds.y, blurredConfidence);
                
                FragColor = mix(vec4(0.0, 1.0, 0.0, 1.0), cameraColor, alpha);
            } else {
                FragColor = cameraColor; 
            }
        }
    """

    fun createCopyProgram(): Int {
        val v = loadShader(GLES30.GL_VERTEX_SHADER, COPY_VERTEX_SHADER)
        val f = loadShader(GLES30.GL_FRAGMENT_SHADER, COPY_FRAGMENT_SHADER)
        val p = GLES30.glCreateProgram()
        GLES30.glAttachShader(p, v)
        GLES30.glAttachShader(p, f)
        GLES30.glLinkProgram(p)
        return p
    }

    fun createCompProgram(): Int {
        val v = loadShader(GLES30.GL_VERTEX_SHADER, COMP_VERTEX_SHADER)
        val f = loadShader(GLES30.GL_FRAGMENT_SHADER, COMP_FRAGMENT_SHADER)
        val p = GLES30.glCreateProgram()
        GLES30.glAttachShader(p, v)
        GLES30.glAttachShader(p, f)
        GLES30.glLinkProgram(p)
        return p
    }

    private fun loadShader(type: Int, shaderCode: String): Int {
        val shader = GLES30.glCreateShader(type)
        GLES30.glShaderSource(shader, shaderCode)
        GLES30.glCompileShader(shader)
        return shader
    }
}